export type TunerLocale = 'pt-BR' | 'en' | 'es';

export const COPY = {
  'pt-BR': {
    tuner: 'Afinador',
    tagline: 'Uma corda. O ajuste certo.',
    subtitle: 'Afine com precisão, de forma simples e rápida.',
    start: 'Iniciar afinador',
    starting: 'Abrindo microfone…',
    chromatic: 'Cromático',
    fine: 'Fino',
    instrument: 'Instrumento',
    tuning: 'Afinação',
    input: 'Entrada',
    referenceA4: 'Referência A4',
    deviceMic: 'Microfone do dispositivo',
    referenceTone: 'Som de referência',
    stopTone: 'Parar som',
    stage: 'Palco',
    exitStage: 'Sair do palco',
    pause: 'Pausar',
    resume: 'Retomar',
    auto: 'Auto',
    stable: 'Sinal estável',
    weak: 'Sinal fraco',
    unstable: 'Sinal instável',
    clipping: 'Entrada saturada',
    ready: 'Toque uma corda por vez.',
    inTune: 'Está afinado',
    tuneDown: 'Baixe um pouco',
    tuneUp: 'Suba um pouco',
    far: 'Fora da faixa',
    permission: 'Permita o acesso ao microfone para medir a afinação.',
    unsupported: 'Este navegador não oferece a captura de áudio necessária.',
    localAudio: 'Áudio processado neste dispositivo',
    advanced: 'Ajustes avançados',
    centsOffset: 'Offset da corda',
    yourInstrument: 'Seu instrumento',
    configure: 'Configure seu instrumento e as preferências de afinação.',
    guitar: 'Guitarra',
    acoustic: 'Violão',
    bass: 'Baixo',
    discover: 'Conhecer o MusicScale',
    copyLink: 'Copiar link',
    copied: 'Link copiado',
    note: 'NOTA',
    string: 'CORDA'
  },
  en: {
    tuner: 'Tuner',
    tagline: 'One string. The right adjustment.',
    subtitle: 'Tune accurately, simply and quickly.',
    start: 'Start tuner',
    starting: 'Opening microphone…',
    chromatic: 'Chromatic',
    fine: 'Fine',
    instrument: 'Instrument',
    tuning: 'Tuning',
    input: 'Input',
    referenceA4: 'A4 reference',
    deviceMic: 'Device microphone',
    referenceTone: 'Reference tone',
    stopTone: 'Stop tone',
    stage: 'Stage',
    exitStage: 'Exit stage',
    pause: 'Pause',
    resume: 'Resume',
    auto: 'Auto',
    stable: 'Stable signal',
    weak: 'Weak signal',
    unstable: 'Unstable signal',
    clipping: 'Input clipping',
    ready: 'Play one string at a time.',
    inTune: 'In tune',
    tuneDown: 'Tune down slightly',
    tuneUp: 'Tune up slightly',
    far: 'Out of range',
    permission: 'Allow microphone access to measure tuning.',
    unsupported: 'This browser does not provide the required audio capture.',
    localAudio: 'Audio processed on this device',
    advanced: 'Advanced settings',
    centsOffset: 'String offset',
    yourInstrument: 'Your instrument',
    configure: 'Configure your instrument and tuning preferences.',
    guitar: 'Guitar',
    acoustic: 'Acoustic guitar',
    bass: 'Bass',
    discover: 'Discover MusicScale',
    copyLink: 'Copy link',
    copied: 'Link copied',
    note: 'NOTE',
    string: 'STRING'
  },
  es: {
    tuner: 'Afinador',
    tagline: 'Una cuerda. El ajuste correcto.',
    subtitle: 'Afina con precisión de forma simple y rápida.',
    start: 'Iniciar afinador',
    starting: 'Abriendo micrófono…',
    chromatic: 'Cromático',
    fine: 'Fino',
    instrument: 'Instrumento',
    tuning: 'Afinación',
    input: 'Entrada',
    referenceA4: 'Referencia A4',
    deviceMic: 'Micrófono del dispositivo',
    referenceTone: 'Sonido de referencia',
    stopTone: 'Detener sonido',
    stage: 'Escenario',
    exitStage: 'Salir del escenario',
    pause: 'Pausar',
    resume: 'Reanudar',
    auto: 'Auto',
    stable: 'Señal estable',
    weak: 'Señal débil',
    unstable: 'Señal inestable',
    clipping: 'Entrada saturada',
    ready: 'Toca una cuerda a la vez.',
    inTune: 'Está afinado',
    tuneDown: 'Baja un poco',
    tuneUp: 'Sube un poco',
    far: 'Fuera de rango',
    permission: 'Permite el acceso al micrófono para medir la afinación.',
    unsupported: 'Este navegador no ofrece la captura de audio necesaria.',
    localAudio: 'Audio procesado en este dispositivo',
    advanced: 'Ajustes avanzados',
    centsOffset: 'Offset de la cuerda',
    yourInstrument: 'Tu instrumento',
    configure: 'Configura tu instrumento y preferencias de afinación.',
    guitar: 'Guitarra',
    acoustic: 'Guitarra acústica',
    bass: 'Bajo',
    discover: 'Conocer MusicScale',
    copyLink: 'Copiar enlace',
    copied: 'Enlace copiado',
    note: 'NOTA',
    string: 'CUERDA'
  }
} as const;
