export type TunerLocale = 'pt-BR' | 'en' | 'es';

export const COPY = {
  'pt-BR': {
    tuner: 'Afinador',
    tagline: 'Uma corda. O ajuste certo.',
    subtitle: 'Afinação profissional, em tempo real, direto no seu navegador.',
    start: 'Iniciar afinador',
    starting: 'Abrindo microfone…',
    chromatic: 'Cromático',
    fine: 'Fino',
    instrument: 'Instrumento',
    tuning: 'Afinação',
    input: 'Entrada',
    referenceA4: 'Referência A4',
    deviceMic: 'Microfone do dispositivo',
    referenceTone: 'Som de referência',
    stopTone: 'Parar som',
    stage: 'Palco',
    exitStage: 'Sair do palco',
    pause: 'Pausar',
    resume: 'Retomar',
    auto: 'Auto',
    stable: 'Sinal estável',
    weak: 'Sinal fraco',
    unstable: 'Sinal instável',
    clipping: 'Entrada saturada',
    ready: 'Toque uma corda por vez.',
    inTune: 'Está afinado',
    tuneDown: 'Baixe um pouco',
    tuneUp: 'Suba um pouco',
    far: 'Fora da faixa',
    permission: 'Permita o acesso ao microfone para medir a afinação.',
    unsupported: 'Este navegador não oferece a captura de áudio necessária.',
    localAudio: 'Áudio processado neste dispositivo',
    advanced: 'Ajustes avançados',
    centsOffset: 'Offset do alvo',
    yourInstrument: 'Seu instrumento',
    configure: 'Configure o instrumento, a afinação e o comportamento do afinador.',
    guitar: 'Guitarra',
    acoustic: 'Violão',
    bass: 'Baixo',
    ukulele: 'Ukulele',
    violin: 'Violino',
    viola: 'Viola de arco',
    cello: 'Violoncelo',
    cavaquinho: 'Cavaquinho',
    discover: 'Conhecer o MusicScale',
    copyLink: 'Copiar link',
    copied: 'Link copiado',
    note: 'NOTA',
    string: 'CORDA',
    measured: 'Medido',
    target: 'Alvo',
    level: 'Entrada',
    clarity: 'Clareza',
    stability: 'Estabilidade',
    live: 'Ao vivo',
    signalCenter: 'Centro',
    diagnostics: 'Diagnóstico de áudio',
    sampleRate: 'Taxa de amostragem',
    analysisWindow: 'Janela',
    processingTime: 'Análise',
    browserProcessing: 'Processamento do navegador',
    rawInput: 'Entrada limpa',
    processedInput: 'Processamento ativo',
    accidental: 'Acidentes',
    sharps: 'Sustenidos',
    flats: 'Bemóis',
    octaveCorrected: 'Oitava corrigida',
    micTip: 'Para maior precisão, toque uma corda isolada e deixe a nota sustentar.',
    fineNotice: 'O modo Fino aumenta a resolução visual; a certificação física de ±0,5 cent só será ativada após validação em aparelhos reais.',
    signalHistory: 'Histórico de afinação',
    dbfs: 'dBFS',
    confidenceHigh: 'Leitura confiável',
    confidenceMedium: 'Adquirindo nota',
    confidenceLow: 'Sinal insuficiente'
  },
  en: {
    tuner: 'Tuner',
    tagline: 'One string. The right adjustment.',
    subtitle: 'Professional real-time tuning, directly in your browser.',
    start: 'Start tuner',
    starting: 'Opening microphone…',
    chromatic: 'Chromatic',
    fine: 'Fine',
    instrument: 'Instrument',
    tuning: 'Tuning',
    input: 'Input',
    referenceA4: 'A4 reference',
    deviceMic: 'Device microphone',
    referenceTone: 'Reference tone',
    stopTone: 'Stop tone',
    stage: 'Stage',
    exitStage: 'Exit stage',
    pause: 'Pause',
    resume: 'Resume',
    auto: 'Auto',
    stable: 'Stable signal',
    weak: 'Weak signal',
    unstable: 'Unstable signal',
    clipping: 'Input clipping',
    ready: 'Play one string at a time.',
    inTune: 'In tune',
    tuneDown: 'Tune down slightly',
    tuneUp: 'Tune up slightly',
    far: 'Out of range',
    permission: 'Allow microphone access to measure tuning.',
    unsupported: 'This browser does not provide the required audio capture.',
    localAudio: 'Audio processed on this device',
    advanced: 'Advanced settings',
    centsOffset: 'Target offset',
    yourInstrument: 'Your instrument',
    configure: 'Configure the instrument, tuning and tuner behavior.',
    guitar: 'Guitar',
    acoustic: 'Acoustic guitar',
    bass: 'Bass',
    ukulele: 'Ukulele',
    violin: 'Violin',
    viola: 'Viola',
    cello: 'Cello',
    cavaquinho: 'Cavaquinho',
    discover: 'Discover MusicScale',
    copyLink: 'Copy link',
    copied: 'Link copied',
    note: 'NOTE',
    string: 'STRING',
    measured: 'Measured',
    target: 'Target',
    level: 'Input',
    clarity: 'Clarity',
    stability: 'Stability',
    live: 'Live',
    signalCenter: 'Center',
    diagnostics: 'Audio diagnostics',
    sampleRate: 'Sample rate',
    analysisWindow: 'Window',
    processingTime: 'Analysis',
    browserProcessing: 'Browser processing',
    rawInput: 'Clean input',
    processedInput: 'Processing active',
    accidental: 'Accidentals',
    sharps: 'Sharps',
    flats: 'Flats',
    octaveCorrected: 'Octave corrected',
    micTip: 'For best precision, play one isolated string and let the note sustain.',
    fineNotice: 'Fine mode increases visual resolution; the ±0.5 cent physical certification stays disabled until real-device validation is complete.',
    signalHistory: 'Tuning history',
    dbfs: 'dBFS',
    confidenceHigh: 'Reliable reading',
    confidenceMedium: 'Acquiring note',
    confidenceLow: 'Insufficient signal'
  },
  es: {
    tuner: 'Afinador',
    tagline: 'Una cuerda. El ajuste correcto.',
    subtitle: 'Afinación profesional en tiempo real, directamente en tu navegador.',
    start: 'Iniciar afinador',
    starting: 'Abriendo micrófono…',
    chromatic: 'Cromático',
    fine: 'Fino',
    instrument: 'Instrumento',
    tuning: 'Afinación',
    input: 'Entrada',
    referenceA4: 'Referencia A4',
    deviceMic: 'Micrófono del dispositivo',
    referenceTone: 'Sonido de referencia',
    stopTone: 'Detener sonido',
    stage: 'Escenario',
    exitStage: 'Salir del escenario',
    pause: 'Pausar',
    resume: 'Reanudar',
    auto: 'Auto',
    stable: 'Señal estable',
    weak: 'Señal débil',
    unstable: 'Señal inestable',
    clipping: 'Entrada saturada',
    ready: 'Toca una cuerda a la vez.',
    inTune: 'Está afinado',
    tuneDown: 'Baja un poco',
    tuneUp: 'Sube un poco',
    far: 'Fuera de rango',
    permission: 'Permite el acceso al micrófono para medir la afinación.',
    unsupported: 'Este navegador no ofrece la captura de audio necesaria.',
    localAudio: 'Audio procesado en este dispositivo',
    advanced: 'Ajustes avanzados',
    centsOffset: 'Offset del objetivo',
    yourInstrument: 'Tu instrumento',
    configure: 'Configura el instrumento, la afinación y el comportamiento del afinador.',
    guitar: 'Guitarra',
    acoustic: 'Guitarra acústica',
    bass: 'Bajo',
    ukulele: 'Ukulele',
    violin: 'Violín',
    viola: 'Viola',
    cello: 'Violonchelo',
    cavaquinho: 'Cavaquinho',
    discover: 'Conocer MusicScale',
    copyLink: 'Copiar enlace',
    copied: 'Enlace copiado',
    note: 'NOTA',
    string: 'CUERDA',
    measured: 'Medido',
    target: 'Objetivo',
    level: 'Entrada',
    clarity: 'Claridad',
    stability: 'Estabilidad',
    live: 'En vivo',
    signalCenter: 'Centro',
    diagnostics: 'Diagnóstico de audio',
    sampleRate: 'Frecuencia de muestreo',
    analysisWindow: 'Ventana',
    processingTime: 'Análisis',
    browserProcessing: 'Procesamiento del navegador',
    rawInput: 'Entrada limpia',
    processedInput: 'Procesamiento activo',
    accidental: 'Alteraciones',
    sharps: 'Sostenidos',
    flats: 'Bemoles',
    octaveCorrected: 'Octava corregida',
    micTip: 'Para mayor precisión, toca una sola cuerda y deja que la nota sostenga.',
    fineNotice: 'El modo Fino aumenta la resolución visual; la certificación física de ±0,5 cent permanece desactivada hasta completar la validación en dispositivos reales.',
    signalHistory: 'Historial de afinación',
    dbfs: 'dBFS',
    confidenceHigh: 'Lectura confiable',
    confidenceMedium: 'Adquiriendo nota',
    confidenceLow: 'Señal insuficiente'
  }
} as const;
